TIMESTAMP_FORMAT_COMPACT_MICROSECONDS = "%Y%m%d%H%M%S%f"
TIMESTAMP_FORMAT_READABLE_MICROSECONDS = "%Y-%m-%d %H:%M:%S.%f"
DEFAULT_DATE_FORMAT = "%Y%m%d"

MAIN_FULL_OUTPUTS_PREFIX = "full_output_main"
MAIN_EXTRACTED_OUTPUTS_PREFIX = "extracted_output_main"
SOV_FULL_OUTPUTS_PREFIX = "full_output_sov"
SOV_EXTRACTED_OUTPUTS_PREFIX = "extracted_output_sov"
RENEWAL_FULL_OUTPUTS_PREFIX = "full_output_renewal"
RENEWAL_EXTRACTED_OUTPUTS_PREFIX = "extracted_output_renewal"

GRAPH_EMAIL_EML_FILE_RESPONSE_FILENAME = "graph_message_eml_response_raw"
CYTORA_MAIN_FILE_NAME = f"{GRAPH_EMAIL_EML_FILE_RESPONSE_FILENAME}_main"
CYTORA_SOV_FILE_NAME = f"{GRAPH_EMAIL_EML_FILE_RESPONSE_FILENAME}_sov"
CYTORA_RENEWAL_FILE_NAME = f"{GRAPH_EMAIL_EML_FILE_RESPONSE_FILENAME}_renewal"
CYTORA_RENEWAL_SLIP_FILE_NAME = "slip_file"

MEDIA_TYPE = "message/rfc822"
