parameters:
  acrImageRepository:
  acrImageTag:

jobs:
  - job: ReplaceTokens
    displayName: Replace Tokens in Helm Chart
    steps:
      - task: qetza.replacetokens.replacetokens-task.replacetokens@6
        displayName: Replace tokens in Helm chart
        inputs:
          sources: |
            '$(System.DefaultWorkingDirectory)/helm-chart/custom-values-template.yaml'
        env:
          ACR_IMAGE_REPOSITORY: ${{ parameters.acrImageRepository }}
          ACR_IMAGE_TAG: ${{ parameters.acrImageTag }}
          
      - publish: '$(System.DefaultWorkingDirectory)/helm-chart/custom-values-template.yaml'
        displayName: Publish Helm custom values yaml for later use
        artifact: 'helm_config.yaml'
